# 在你自己的配置下方再添加以下配置，如果有重复的不要反复添加

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  dashboards:
    mattias-lovelace:
      mode: yaml
      title: Tablet
      icon: mdi:tablet-cellphone
      show_in_sidebar: true
      filename: dashboards/tablet/ui-lovelace.yaml